# 使用throw敘述拋出例外
- 錯誤寫法
1. 沒有定義a,b為數值型態
2. 被除數不能為0否則為無窮大
    ```JavaScript 
    function div(a,b) {
        return a/b;
      }
    var res = div(3,4);
    console.log(res);

    // =======正確寫法==========
    function div(a,b) {
        if((typeof a) != "number"||(typeof b) != "number"){
            throw "must be Number value";
        }
        if(!isFinite(a) || !isFinite(b)){
            throw "must be finity";
        }
        if(b===0){
            throw "Dividend must not be 0";
        }
        return a/b;
      }
      ```
- 將錯誤反饋形成物件
    ```JavaScript 
    var InputError = {
        NotNumberError:"must be Number value",
        FinityError:"must be finity",
        DividendError:"Dividend must not be 0"
    };
    function div(a,b) { 
        if((typeof a ) != "number" || (typeof b) != "number"){
            throw InputError.NotNumberError;
        }   
     }
     ```
# 例外的捕捉與處理

- JavaScript中的**try-catch-finally** 
- 程式執行時期拋出例外後會直接中斷，應該要想辦法**跳過**這個例外，並將錯誤資訊提供給使用者
- **try**執行可能有例外的程式 -> 如有例外則拋給**catch** -> 最後執行**finally**程式區塊中的程式
    ```JavaScript 
    var InputError = {
        NotNumberError:"must be Number value",
        FinityError:"must be finity",
        DividendError:"Dividend must not be 0"
    };
    function div(a,b){
        if((typeof a) != "number"||(typeof b) != "number"){
            throw InputError.NotNumberError;
        }
        if(!isFinite(a) || !isFinite(b)){
            throw InputError.FinityError;
        }
        if(b===0){
            throw InputError.DividendError;
        }
        return a/b;
    } 
    try{
        var res = div("3",4);
    }catch(e){
        console.log(e);
    }finally{
        console.log("例外處理結束");
    }
    console.log(res);
    ```
# 例外的傳遞及分層處理
- 將例外處理邏輯封裝進新的函數內部，方便其他開發者呼叫
- 如沒有針對例外進行處理，則例外會繼續向上傳遞到呼叫方，直到被捕捉
    ```JavaScript 
    var InputError = {
        NotNumberError:"must be Number value",
        FinityError:"must be finity",
        DividendError:"Dividend must not be 0"
    };
    function div(a,b){
        if((typeof a) != "number"||(typeof b) != "number"){
            throw InputError.NotNumberError;
        }
        if(!isFinite(a) || !isFinite(b)){
            throw InputError.FinityError;
        }
        if(b===0){
            throw InputError.DividendError;
        }
        return a/b;
    }
    function newDiv(a,b){
        try{
            var res = div(a,b);
        }catch(e){
            if(e===InputError.DividendError){
                res = NaN;
            }else if(e===InputError.FinityError){
                res = NaN;
            }else{
                throw e;
            }
        }finally{
            console.log("例外處理結束");
        }
        return res;
    }
    try{
        var res = newDiv(Infinity,1);
    }catch(e){
        console.log("輸入錯誤");
    }finally{
        console.log("外層例外處理結束")
    }
    console.log(res);
    ```
 